menu:
#- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- {name: 'press', url: '/news-coverage'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Sarthak Chaturvedi', title: 'Staff Scientist', department: 'Energy & Environment Directorate', institution: 'Pacific Northwest National Laboratory', institution_address: '902 Battelle Blvd, Richland, WA', phone: '(509) 375-2594', email: 'sarthak.chaturvedi@pnnl.gov', office: 'Research Operations Building', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

featured_news_coverage:
  - {title: 'White House CEQ Report Features Work on Modernizing Environmental Reviews', publication: 'White House Council on Environmental Quality', date: '2024-09-02', summary: 'My contributions to AI-driven environmental review modernization were featured in a White House CEQ report.', image: 'assets/img/White_House.webp', url: 'ceq-policyai-report'}
  - {title: 'Contributing Author to Key DOE Report on AI in Energy', publication: "U.S. Department of Energy", date: '2024-04-29', summary: "I contributed to a significant DOE report, highlighted in a major announcement, on AI's potential to transform the energy sector.", image: 'assets/img/doe_logo.png', url: 'doe-ai-energy-report'}
  - {title: 'Mentioned in White House Report on AI Actions', publication: 'White House Briefing', date: '2024-04-29', summary: 'A White House report on key AI actions recognized my work on an AI project supporting clean energy infrastructure development.', image: 'assets/img/White_House.webp', url: 'white-house-ai-recognition'}

news_coverage:
  - {title: 'White House CEQ Report Features Work on Modernizing Environmental Reviews', publication: 'White House Council on Environmental Quality', date: '2024-09-02', summary: 'My contributions to AI-driven environmental review modernization were featured in a White House CEQ report.', image: 'assets/img/White_House.webp', url: 'ceq-policyai-report'}
  - {title: 'Contributing Author to Key DOE Report on AI in Energy', publication: "U.S. Department of Energy", date: '2024-04-29', summary: "I contributed to a significant DOE report, highlighted in a major announcement, on AI's potential to transform the energy sector.", image: 'assets/img/doe_logo.png', url: 'doe-ai-energy-report'}
  - {title: 'Mentioned in White House Report on AI Actions', publication: 'White House Briefing', date: '2024-04-29', summary: 'A White House report on key AI actions recognized my work on an AI project supporting clean energy infrastructure development.', image: 'assets/img/White_House.webp', url: 'white-house-ai-recognition'}
  - {title: 'Highlighted in DOE Announcement on AI Actions', publication: "U.S. Department of Energy", date: '2024-04-29', summary: "A DOE announcement on actions to enhance America's AI leadership showcased an AI project I contribute to.", image: 'assets/img/doe_logo.png', url: 'doe-policyai-feature'}

social:
- {icon: 'github', link: 'https://github.com/sarthakchat/'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/sarthak-chaturvedi/'}

contacts:
- {name: 'Sarthak Chaturvedi', title: 'Staff Scientist', department: 'Energy & Environment Directorate', company: 'United States Department of Energy', institution: 'Pacific Northwest National Laboratory', institution_address: '902 Battelle Blvd, Richland, WA', phone: '(509) 375-2594', email: '[firstname].[lastname]@pnnl.gov', office: 'Research Operations Building', image: 'assets/img/contact.jpg'}
