menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- {name: 'news coverage', url: '/news-coverage'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Sarthak Chaturvedi', title: 'Staff Scientist', department: 'Energy & Environment Directorate', institution: 'Pacific Northwest National Laboratory', institution_address: '902 Battelle Blvd, Richland, WA', phone: '(509) 375-2594', email: 'sarthak.chaturvedi@pnnl.gov', office: 'Research Operations Building', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

news_coverage:
- {title: 'PolicyAI featured in White House Briefing', 
publication: 'White House Briefing', 
date: '2024-04-29', 
summary: 'Our work has been recognized at the highest levels of government: 
🏛️ White House Spotlight: Our efforts in AI-driven environmental permitting have been highlighted in a recent White House briefing on AI actions.
🔍 Key Mention: The White House statement specifically noted, 'DOE is piloting AI tools to streamline permitting processes and improving siting for clean energy infrastructure.'
This recognition underscores the importance of our work in policyAI and environmental permitting, demonstrating its potential to drive significant improvements in clean energy development', 
image: 'assets/img/graduate-student.jpg', 
url: 'https://www.whitehouse.gov/briefing-room/statements-releases/2024/04/29/biden-harris-administration-announces-key-ai-actions-180-days-following-president-bidens-landmark-executive-order/'}
- {title: 'New Policy Framework for Sustainable Energy', publication: 'Energy Policy Journal', date: '2023-11-22', summary: 'Groundbreaking policy framework proposed for sustainable energy adoption.', image: 'assets/img/graduate-student.jpg', url: 'ai-energy-systems'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Sarthak Chaturvedi', title: 'Staff Scientist', department: 'Energy & Environment Directorate', company: United States Department of Energy , institution: 'Pacific Northwest National Laboratory', institution_address: '902 Battelle Blvd, Richland, WA', phone: '(509) 375-2594', email: 'sarthak.chaturvedi@pnnl.gov', office: 'Research Operations Building', image: 'assets/img/contact.jpg'}
