menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- {name: 'news coverage', url: '/news-coverage'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Sarthak Chaturvedi', title: 'Staff Scientist', department: 'Energy & Environment Directorate', institution: 'Pacific Northwest National Laboratory', institution_address: '902 Battelle Blvd, Richland, WA', phone: '(509) 375-2594', email: 'sarthak.chaturvedi@pnnl.gov', office: 'Research Operations Building', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

news_coverage:
- {title: 'White House Recognizes AI Work in Clean Energy Infrastructure Permitting', publication: 'White House Briefing', date: '2024-04-29', summary: 'Our AI-driven environmental permitting work highlighted in White House briefing on AI actions.', image: 'assets/img/White_House.webp', url: 'white-house-ai-recognition'}
- {title: 'DOE Features PolicyAI Project at PNNL', publication: 'Department of Energy', date: '2024-04-29', summary: 'DOE article highlights our PolicyAI work at PNNL for clean energy infrastructure development.', image: 'assets/img/doe_logo.png', url: 'doe-policyai-feature'}
social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Sarthak Chaturvedi', title: 'Staff Scientist', department: 'Energy & Environment Directorate', company: United States Department of Energy , institution: 'Pacific Northwest National Laboratory', institution_address: '902 Battelle Blvd, Richland, WA', phone: '(509) 375-2594', email: 'sarthak.chaturvedi@pnnl.gov', office: 'Research Operations Building', image: 'assets/img/contact.jpg'}
